# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sam Beales
tagline:          'My accomplishments'
description:      'Bioinformatics and Immunology'
url:              https://sam-beales.uk/
baseurl:          /

author:
  name:           'Sam Beales'
  url:            https://www.linkedin.com/in/sam-beales-614624183/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
